### ISSUE TITLE
How do you work with multiple `CMakeLists.txt` properly?

### ISSUE THREAD

**Issue by VicoHBB** [Civitasv/cmake-tools.nvim#150]
I created a simple template to work on C++ with CMake, with the following structure:

```bash
 Template
 ├── app
 │   ├── CMakeLists.txt
 │   └── main.cpp
 ├── lib
 │   ├── inc
 │   │   ├── CMakeLists.txt
 │   │   └── my_lib.hpp
 │   └── src
 │       ├── Build_Release
 │       ├── CMakeLists.txt
 │       └── my_lib.cpp
 └── CMakeLists.txt
```

And I use `cmake`  with the following commands:

```bash
mkdir build
cmake ..
cmake --build .
./app/Executable
```

Everything works right when I execute the commands on the terminal, but when I tried to run the `CMakeGenerate` command, the Build directory is created inside `/lib/src/` like this:

```bash
 Template
 ├── app
 │   ├── CMakeLists.txt
 │   └── main.cpp
 ├── lib
 │   ├── inc
 │   │   ├── CMakeLists.txt
 │   │   └── my_lib.hpp
 │   └── src
 │       ├── Build_Release
 │       ├── CMakeLists.txt
 │       └── my_lib.cpp
 └── CMakeLists.txt
```
Also, I checked the working directory, and it looks good, but I don't know why the Build directory is created inside the `/lib/src`; I don't think that is a problem inside `CMakeLists.txt` files because if I run `cmake` manually works well. 

If anyone has a suggestion, I'd appreciate it.

**Comment by rohit-kumar-j** [comment]
Based on what you described, I can only think of this...

Where do you open nvim from?
```bash
/home/username/Template/lib/src $~ nvim

# or

/home/username/Template $~ nvim
```

Because if you open from the `lib/src`, then the root directory will be detected as `lib/src`, so the build directory is resolved from there.

**Comment by Civitasv** [comment]
Yes, you should check your working directory.

**Comment by VicoHBB** [comment]
> Based on what you described, I can only think of this...
> 
> Where do you open nvim from?
> 
> ```shell
> /home/username/Template/lib/src $~ nvim
> 
> # or
> 
> /home/username/Template $~ nvim
> ```
> 
> Because if you open from the `lib/src`, then the root directory will be detected as `lib/src`, so the build directory is resolved from there.

Like the second one, also I tried to move to the directory and start `nvim` like this:
```bash
$ cd /home/username/Template
$ nvim .
```
But still doesn't work

**Comment by VicoHBB** [comment]
> Yes, you should check your working directory. By default, it is `vim.loop.cwd()`, and you can also change it using `CMakeSelectCwd`.

Thanks! The command  `CMakeSelectCwd` solves the trouble but I need to run it every time that I want to work on the project

**Comment by Civitasv** [comment]
We already save your choice of cwd in session file. I think you don't need to run it every time. What do you mean by running it every time?

**Comment by rohit-kumar-j** [comment]
> > Yes, you should check your working directory. By default, it is `vim.loop.cwd()`, and you can also change it using `CMakeSelectCwd`.
> 
> Thanks! The command `CMakeSelectCwd` solves the trouble but I need to run it every time that I want to work on the project

I think he's having problems with the cache. Try deleting the contents of `cmake_tools_nvim/**` directory, and then opening vim from the correct directory.

```
    unix = vim.fn.expand("~") .. "/.cache/cmake_tools_nvim/",
    mac = vim.fn.expand("~") .. "/.cache/cmake_tools_nvim/",
    win = vim.fn.expand("~") .. "/AppData/Local/cmake_tools_nvim/",
```

**Comment by Civitasv** [comment]
Any more questions? Closing it for now, feel free to open it.

**Comment by VicoHBB** [comment]
First of all, sorry for the late reply,  but I am writing the solution if it can help someone. After trying a couple of things, it seems that the problem was that I copied the template with all the files generated after running the command `CMakeBuild`, then I just cleaned the project from all the generated files. After this when copying this template to another path everything works fine.
It may be a silly bug, but I'm just finishing to understand how CMake works; if anyone can describe the error, I'd really appreciate it. :)
