### ISSUE TITLE
Wrong arguments passed to Overseer

### ISSUE THREAD

**Issue by lucas-yotsui** [Civitasv/cmake-tools.nvim#159]
**Bug description**
When I try to use Overseer as my executor it fails, apparently for passing the wrong cmake executable. here's the output I get in notify:

![error](https://i.imgur.com/bqS5bUC.png)

From this error I assume that the command passed to Overseer is wrong, since as you can see on the screenshot it is calling '  & /snap/bin/cmake' instead of just '/snap/bin/cmake'. The question now is: Is it something I configured wrong or is it an issue with the extension?

**Steps to reproduce**
here's my setup for the extension:

```lua
cmake.setup({
    cmake_command = '/snap/bin/cmake',
    cmake_build_directory = "build", -- this is used to specify generate directory for cmake, allows macro expansion
    cmake_kits_path = "/home/lucas-yotsui/.local/share/CMakeTools/cmake-tools-kits.json",
    cmake_executor = {               -- executor to use
        name = "overseer",           -- name of the executor
        opts = {
            new_task_opts = {},      -- options to pass into the `overseer.new_task` command
            on_new_task = function(task)
                task:subscribe("on_complete", LaunchEvent)
            end,
        },
    },
    cmake_terminal = {
        name = "terminal",
        opts = {
            name = "Terminal",
            prefix_name = "[CMakeTools]: ", -- This must be included and must be unique, otherwise the terminals will not work. Do not use a simple spacebar " ", or any generic name
            split_direction = "horizontal", -- "horizontal", "vertical"
            split_size = 11,

            -- Window handling
            single_terminal_per_instance = true,  -- Single viewport, multiple windows
            single_terminal_per_tab = true,       -- Single viewport per tab
            keep_terminal_static_location = true, -- Static location of the viewport if avialable

            -- Running Tasks
            start_insert_in_launch_task = true, -- If you want to enter terminal with :startinsert upon using :CMakeRun
            start_insert_in_other_tasks = true, -- If you want to enter terminal with :startinsert upon launching all other cmake tasks in the terminal. Generally set as false
            focus_on_main_terminal = true,      -- Focus on cmake terminal when cmake task is launched. Only used if executor is terminal.
            focus_on_launch_terminal = true,    -- Focus on cmake launch terminal when executable target in launched.
        },
    },
    cmake_dap_configuration = { -- debug settings for cmake
        name = "cpp",
        type = "lldb",
        request = "launch",
        stopOnEntry = false,
        runInTerminal = true,
        console = "integratedTerminal",
    },
})
```
**Expected behavior**
I was hoping that it would execute the command with Overseer

**Environment**
- OS: Ubuntu on WSL2

**Comment by rohit-kumar-j** [comment]
related #158

**Comment by Civitasv** [comment]
> I think this
> 
> https://github.com/Civitasv/cmake-tools.nvim/blob/714fcd7ce88d320507d3a4a1da5d23bf457bcf7b/lua/cmake-tools/executors/overseer.lua#L19
> 
> should be `&&` and not `&`. Would this be the source of the error @Civitasv ?

I think you're right.

**Comment by Civitasv** [comment]
I've pushed a fix.

**Comment by lucas-yotsui** [comment]
Still not working, I now get the same error message but with two '&' instead of one.

After seeing @rohit-kumar-j's comment and looking into the code a bit, I found that this env_script is passed by the cmake kit environmentSetupScript variable. I've checked and none of my kits have such field set to anything, so I tried to set it on the json file manually but it gave me these two output notifications:

![new error part1](https://i.imgur.com/yhVMS5G.png)
![new error part2](https://i.imgur.com/tJTqW6z.png)

From the 127 error, I assume some of the executables is not being found, which is odd since I pass the full path to the cmake program. It is not anything on the _dummy.sh_ file for it is completely empty. I've made sure my cmake path is correct and all, now I don't know what else it could be. My best educated guess is that passing the setup script like that is causing the issue. 

Personally I've never used this such script in any of my kits, is it possible to make this env_script optional somehow? Maybe as a variable on setup like _**use_env_script**_ or check if the variable is empty before appending it with &&.

**Comment by rohit-kumar-j** [comment]
> Personally I've never used this such script in any of my kits, is it possible to make this env_script optional somehow? Maybe as a variable on setup like _**use_env_script**_ or check if the variable is empty before appending it with &&.

Ah yes, this... I have to add support for windows as I am running a few commits behind. For now you can roll back to this commit (before envScript was added):

```lua
return { --lazy.nvim config
  "Civitasv/cmake-tools.nvim",
  commit = "86bad7cb3ebc1cac51046e88cf62d5b962e8a1cc",
  config = function()
    require("cmake-tools").setup({
      -- Setup
    })
  end
}
```

**Comment by lucas-yotsui** [comment]
> > Personally I've never used this such script in any of my kits, is it possible to make this env_script optional somehow? Maybe as a variable on setup like _**use_env_script**_ or check if the variable is empty before appending it with &&.
> 
> Ah yes, this... I have to add support for windows as I am running a few commits behind. For now you can roll back to this commit (before envScript was added):
> 
> ```lua
> return { --lazy.nvim config
>   "Civitasv/cmake-tools.nvim",
>   commit = "86bad7cb3ebc1cac51046e88cf62d5b962e8a1cc",
>   config = function()
>     require("cmake-tools").setup({
>       -- Setup
>     })
>   end
> }
> ```

I've actually forked the repo as I have a few other changes I needed to make, but removing this env_script indeed made it work.

**Comment by rohit-kumar-j** [comment]
@Civitasv , #160 rolls back envScript temporarily for overseer so master branch work without issues for now.

**Comment by Civitasv** [comment]
Okay.

**Comment by Civitasv** [comment]
Closing for now, feel free to open it if you still have problem.
